# =========================================================
# GLOBAL DEFAULT CONFIG (ใช้ร่วมทุกโปรไฟล์)
# =========================================================
server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # แสดง error message แบบละเอียด (เช่น validation errors)
  error:
    include-message: always
    include-binding-errors: always

trash:
  retention-days: 1
# =========================================================
# 🔹 DEV PROFILE (ใช้เวลา run ใน IntelliJ / Local)
# =========================================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/capstone?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: root
    password: Dear_pim25

  jpa:
    hibernate:
      ddl-auto: validate   # dev ให้ auto สร้างตารางได้

firebase:
  config:
    path: classpath:firebase/firebase-adminsdk.json


# =========================================================
# 🔹 CONTAINER PROFILE (ใช้ตอนรันใน Docker / VM)
# =========================================================
---
spring:
  config:
    activate:
      on-profile: container

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate    # ใน container ไม่ให้ spring ไปสร้าง/แก้ schema เอง

# Firebase จะใช้ Application Default Credentials (ADC)
# ซึ่งมาจาก env GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase.json

