# =========================================================
# GLOBAL DEFAULT CONFIG (ใช้ร่วมทุกโปรไฟล์)
# =========================================================
server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  error:
    include-message: always
    include-binding-errors: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

servlet:
  multipart:
    max-file-size: 5MB
    max-request-size: 5MB

trash:
  retention-days: 30

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

line:
  channel:
    access-token: ${LINE_CHANNEL_ACCESS_TOKEN}
    secret: ${LINE_CHANNEL_SECRET}
  login:
    channel-id: ${LINE_LOGIN_CHANNEL_ID}
    channel-secret: ${LINE_LOGIN_CHANNEL_SECRET}
    redirect-uri: https://bscit.sit.kmutt.ac.th/capstone25/cp25nw2/api/line/callback
    state-secret: ${LINE_STATE_SECRET}
#    redirect-uri: https://uneffectively-noncompulsory-temika.ngrok-free.dev/api/line/callback

app:
  frontend-url: https://bscit.sit.kmutt.ac.th/capstone25/cp25nw2

# =========================================================
# 🔹 DEV PROFILE (ใช้เวลา run ใน IntelliJ / Local)
# =========================================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/capstone?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Bangkok
    username: root
    password: Dear_pim25

  jpa:
    hibernate:
      ddl-auto: validate
      # dev ให้ auto สร้างตารางได้

firebase:
  config:
    path: classpath:firebase/firebase-adminsdk.json

line:
  login:
    redirect-uri: https://uneffectively-noncompulsory-temika.ngrok-free.dev/api/line/callback

app:
  frontend-url: http://localhost:5173
# =========================================================
# 🔹 CONTAINER PROFILE (ใช้ตอนรันใน Docker / VM)
# =========================================================
---
spring:
  config:
    activate:
      on-profile: container

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate    # ใน container ไม่ให้ spring ไปสร้าง/แก้ schema เอง

# Firebase จะใช้ Application Default Credentials (ADC)
# ซึ่งมาจาก env GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/firebase.json